#Escreva um programa que leia um valor em metros e o exiba convertido em centímetros e milímetros.
print ('Calculadora de conversão')
pulalinha = ('=')
print ('{:=^24}'.format(pulalinha))
m = float(input('Digite uma distância em metro(m): '))
print ('{:=^30}'.format(pulalinha))
km = float(m/1000)
hm = float(m/100)
dam = float(m/10)
dm = float(m*10)
cm = float(m*100)
mm = float(m*1000)
print ('A medida de {:.2f}m corresponde a: \n {:.2f}km \n {:.2f}hm \n {:.2f}dam \n {:.2f}dm \n {:.2f}cm \n {:.2f}mm.'.format(m, km, hm, dam, dm, cm, mm))
