#Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.
cr = ('=')
print('{:=^25}'.format(cr))
print('Identificador de tabuada.')
ql = ('-')
print('{:-^25}'.format(ql))
n = int(input('Digite um número (0-9): '))
n1 = int(n*1)
print(n,' x 1  =  ', n1)
n2 = int(n*2)
print(n,' x 2  =  ', n2)
n3 = int(n*3)
print(n,' x 3  =  ', n3)
n4 = int(n*4)
print(n,' x 4  =  ', n4)
n5 = int(n*5)
print(n,' x 5  =  ', n5)
n6 = int(n*6)
print(n,' x 6  =  ', n6)
n7 = int(n*7)
print(n,' x 7  =  ', n7)
n8 = int(n*8)
print(n,' x 8  =  ', n8)
n9 = int(n*9)
print(n,' x 9  =  ', n9)
n10 = int(n*10)
print(n, ' x 10 =  ', n10)
print('{:=^25}'.format(cr))
