#Crie um programa que leia quanto dinheiro uma pessoa tem na certeira e mostre quantos Dólares ela pode comprar. Dólar hoje 01/09/25 - R$ 5,44
cbç = ('#')
print ('{:#^50}'.format(cbç))
print ('Carteira conversora Real (R$) para Dólar (US$).')
ql = ('=')
print ('{:=^50}'.format(ql))
real = float(input('Digite o valor em Real você tem em carteira: '))
dolar = float(5.44)
compradol = float(real/dolar)
traço = ('-')
print ('{:-^50}'.format(traço))
print ('Voce pode compar {:.2f} US$'.format(compradol))
print ('{:#^50}'.format(cbç))
